= Google Cloud Services - Firebase

This extension implements DevServices for applications developed on with the Google Firebase platform. The DevService runs the appropriate emulators of the Firebase platform based on your configuration.

Be sure to have read the https://quarkiverse.github.io/quarkiverse-docs/quarkus-google-cloud-services/main/index.html[Google Cloud Services extension pack global documentation] before this one, it contains general configuration and information.

== Current status

The following emulators have been verified to work:
* Firebase Auth
* Firebase Firestore
* Firebase Emulator UI

The following emulators need additional work:
* Firebase Hosting
* Realtime Database
* Functions
* PubSub

The following emulators are currently not supported:
* EventArc
* Cloud Storage

== Bootstrapping the project

First, we need a new project. Create a new project with the following command (replace the version placeholder with the correct one):

[source, shell script]
----
mvn io.quarkus:quarkus-maven-plugin:${quarkusVersion}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=firebase-admin-quickstart \
    -Dextensions="quarkus-google-cloud-firebase"
cd firebase-admin-quickstart
----

This command generates a Maven project, importing the Google Cloud Firebase extension.

If you already have your Quarkus project configured, you can add the `quarkus-google-cloud-firebase` extension to your project by running the following command in your project base directory:

[source, shell script]
----
./mvnw quarkus:add-extension -Dextensions="quarkus-google-cloud-firebase"
----

This will add the following to your pom.xml:

[source, xml]
----
<dependency>
    <groupId>io.quarkiverse.googlecloudservices</groupId>
    <artifactId>quarkus-google-cloud-firebase</artifactId>
</dependency>
----

== Configuration

* `quarkus.google.cloud.project-id` - The project ID is mandatory for projects using Firebase Auth (Firebase Admin).
* `quarkus.google.cloud.firebase.devservice.image-name` - The base image name to use (see Custom Docker images below)
* `quarkus.google.cloud.firebase.devservice.firebase-version` - The version of the firebase tools to use. Default is to use the latest available version.
* `quarkus.google.cloud.firebase.devservice.token` - The firebase token to use. This is mandatory when using Hosting. This token can be generated using the firebase CLI.
* `quarkus.google.cloud.firebase.devservice.custom-firebase-json` - The path to a custom `firebase.json` file to use instead of the auto generated one (see Custom Firebase.json)
* `quarkus.google.cloud.firebase.devservice.java-tool-options` - Java tool options to pass to the Java based emulators (like -Xmx)
* `quarkus.google.cloud.firebase.devservice.emulator-data` - Path to a directory where to import and export (on exit) the emulator data.
* `quarkus.google.cloud.firebase.devservice.ui.enabled` - Whether to enable the Emulator UI. The default is true.

*Firebase auth emulator*

* `quarkus.google.cloud.firebase.auth.devservice.enabled` - Enable the Firebase Auth emulator. The default is false.
* `quarkus.google.cloud.firebase.auth.devservice.emulatorPort` - The port on which to expose the emulator from the Docker container. The default is to expose the service on a random port.

*Hosting emulator*

* `quarkus.google.cloud.firebase.hosting.devservice.enabled` - Enable the Hosting emulator. The default is false.
* `quarkus.google.cloud.firebase.hosting.devservice.emulatorPort` - The port on which to expose the emulator from the Docker container. The default is to expose the service on a random port.

*Realtime database emulator*

* `quarkus.google.cloud.database.devservice.enabled` - Enable the Realtime database emulator. The default is false.
* `quarkus.google.cloud.database.devservice.emulatorPort` - The port on which to expose the emulator from the Docker container. The default is to expose the service on a random port.

*Firestore emulator*

* `quarkus.google.cloud.firestore.devservice.enabled` - Enable the Firestore emulator. The default is false.
* `quarkus.google.cloud.firestore.devservice.emulatorPort` - The port on which to expose the emulator from the Docker container. The default is to expose the service on a random port.

*Functions emulator*

* `quarkus.google.cloud.functions.devservice.enabled` - Enable the Firestore emulator. The default is false.
* `quarkus.google.cloud.functions.devservice.emulatorPort` - The port on which to expose the emulator from the Docker container. The default is to expose the service on a random port.

*PubSub emulator*

* `quarkus.google.cloud.pubsub.devservice.enabled` - Enable the Firestore emulator. The default is false.
* `quarkus.google.cloud.pubsub.devservice.emulatorPort` - The port on which to expose the emulator from the Docker container. The default is to expose the service on a random port.

== Custom Docker image

To run the emulators, a custom Docker image is build on the fly to run the Firebase emulators. This image is based on a NodeJS based image (refer to the configuration of the default value of `quarkus.google.cloud.firebase.devservice.image-name` to see the base image).

You can configure a custom image if needed as base image to run the Firebase Emulators in. This image has the following requirements:

* The image must support NodeJS in a version compatible with the required Firebase Tools
* The image must be `alpine` based (or at least able to install the following packages using `apk`: )
** openjdk11-jre
** bash
** curl
** openssl
** gettext
** nano
** nginx
** sudo

== Custom Firebase JSON

By default a `firebase.json` file is generated inside the image to configure the various emulators. You can configure the DevService to use your own custom firebase.json file (e.g generated using the Firebase tools CLI). The following requirements are defined for this file:

* Each of the emulators must be exposed on `0.0.0.0` as host as described https://firebase.google.com/docs/emulator-suite/use_hosting#emulators-no-local-host[here]. If this is not done, the Emulators will not be reachable from the Docker host.
* Emulators need to be configured to use the default ports. Customizing the ports on which they run is currently not supported (this might change in a future version).

== Interaction with other other extensions

The following extensions support a DevService which conflicts with the DevService exposed by the Firebase Emulators.

* Firestore
* PubSub
* TODO: Verify Storage

When including this module, these DevServices will automatically be disabled, as the Firebase emulator should feature wise be on-par or more extensive than the individual emulators.